@ECHO OFF
SETLOCAL

SET "HDCODEX_LINEAR_INPUT=%~1"
SET "HDCODEX_DISPLAY_OUTPUT=%~2"
SET "HDCODEX_DISPLAY_EXPOSURE=%~3"
IF "%HDCODEX_LINEAR_INPUT%"=="" EXIT /B 2
IF "%HDCODEX_DISPLAY_OUTPUT%"=="" EXIT /B 2
IF "%HDCODEX_DISPLAY_EXPOSURE%"=="" SET "HDCODEX_DISPLAY_EXPOSURE=0"

IF NOT DEFINED USDEXTRA CALL "%~dp0setup_usd_env.bat"
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
SET "HDCODEX_DISPLAY_TRANSFORM=%USDEXTRA%\bin\hdCodexDisplayTransform.exe"
SET "HDCODEX_DISPLAY_TEMP=%~dp1%~n1-display%~x2"

IF NOT EXIST "%HDCODEX_LINEAR_INPUT%" (
  ECHO Linear gallery input does not exist: %HDCODEX_LINEAR_INPUT%
  EXIT /B 1
)
IF NOT EXIST "%HDCODEX_DISPLAY_TRANSFORM%" (
  ECHO Gallery display transform is not installed. Run compile.bat first.
  EXIT /B 1
)
IF EXIST "%HDCODEX_DISPLAY_TEMP%" DEL /Q "%HDCODEX_DISPLAY_TEMP%"

"%HDCODEX_DISPLAY_TRANSFORM%" "%HDCODEX_LINEAR_INPUT%" "%HDCODEX_DISPLAY_TEMP%" --exposure "%HDCODEX_DISPLAY_EXPOSURE%"
IF ERRORLEVEL 1 EXIT /B %ERRORLEVEL%
IF NOT EXIST "%HDCODEX_DISPLAY_TEMP%" (
  ECHO Display transform did not create %HDCODEX_DISPLAY_TEMP%.
  EXIT /B 1
)
COPY /Y "%HDCODEX_DISPLAY_TEMP%" "%HDCODEX_DISPLAY_OUTPUT%" >NUL
EXIT /B %ERRORLEVEL%
