#include "hdcodex/materialx/materialx_compiler.h"

#include "pxr/imaging/hdMtlx/hdMtlx.h"

#include <MaterialXCore/Util.h>
#include <MaterialXFormat/XmlIo.h>
#include <MaterialXGenGlsl/VkShaderGenerator.h>
#include <MaterialXGenShader/GenContext.h>
#include <MaterialXGenShader/HwShaderGenerator.h>
#include <MaterialXGenShader/Shader.h>
#include <MaterialXGenShader/Util.h>

#include <stdexcept>
#include <string>
#include <set>

namespace hdcodex {
namespace {

MaterialX::FileSearchPath MaterialXSearchPaths()
{
    MaterialX::FileSearchPath paths = pxr::HdMtlxSearchPaths();
    paths.prepend(MaterialX::FilePath(HDCODEX_MATERIALX_DATA_ROOT));
    return paths;
}

bool IsMaterialXUsdPrimvarReader(const MaterialX::NodePtr& node)
{
    if (!node || node->getCategory() != "UsdPrimvarReader") return false;
    const MaterialX::NodeDefPtr nodeDef = node->getNodeDef();
    return nodeDef && nodeDef->getName().starts_with("ND_UsdPrimvarReader_");
}

void FlattenMaterialXUsdPrimvarReaders(const MaterialX::DocumentPtr& document)
{
    // MaterialX 1.39.3 does not propagate the interface value on the
    // ND_UsdPrimvarReader_* NodeGraph implementation when that reader is
    // nested in another NodeGraph.  Flatten just this standard-library
    // implementation with MaterialX's own graph operation so that `varname`
    // is transferred to the implementation's `geomprop` input before shader
    // generation.  This preserves the authored MaterialX implementation; it
    // does not substitute renderer-authored shader behavior.
    const MaterialX::NodePredicate predicate =
        [](const MaterialX::NodePtr& node) {
            return IsMaterialXUsdPrimvarReader(node);
        };
    document->flattenSubgraphs(MaterialX::EMPTY_STRING, predicate);
    for (const MaterialX::NodeGraphPtr& graph : document->getNodeGraphs()) {
        graph->flattenSubgraphs(MaterialX::EMPTY_STRING, predicate);
    }
}

bool IsMaterialXSurfaceModelOrUsdPrimvarReader(const MaterialX::NodePtr& node)
{
    if (!node) return false;
    const MaterialX::NodeDefPtr nodeDef = node->getNodeDef();
    if (!nodeDef) return false;
    const std::string& name = nodeDef->getName();
    return name == "ND_open_pbr_surface_surfaceshader" ||
        name == "ND_standard_surface_surfaceshader" ||
        name.starts_with("ND_UsdPreviewSurface_") ||
        name.starts_with("ND_UsdPrimvarReader_");
}

void FlattenMaterialXSurfaceModels(const MaterialX::DocumentPtr& document)
{
    // Expand high-level surface models into their MaterialX primitive closure
    // graphs. Keep ordinary value nodes intact: their target implementations
    // will be generated by the closure backend, and recursively flattening the
    // entire standard library would create a needlessly large intermediate.
    const MaterialX::NodePredicate predicate =
        [](const MaterialX::NodePtr& node) {
            return IsMaterialXSurfaceModelOrUsdPrimvarReader(node);
        };
    for (const MaterialX::NodeGraphPtr& graph : document->getNodeGraphs()) {
        graph->flattenSubgraphs(MaterialX::EMPTY_STRING, predicate);
    }
    document->flattenSubgraphs(MaterialX::EMPTY_STRING, predicate);
}

MaterialX::NodePtr ConnectedNode(
    const MaterialX::InputPtr& input,
    std::string* outputName = nullptr)
{
    if (!input) return {};
    if (const MaterialX::OutputPtr output = input->getConnectedOutput()) {
        if (outputName) *outputName = output->getName();
        if (const MaterialX::NodePtr node = output->getConnectedNode()) return node;
    }
    if (outputName) *outputName = input->getOutputString();
    return input->getConnectedNode();
}

void AppendProgramNode(
    const MaterialX::NodePtr& node,
    MaterialXGeneratedProgram& program,
    std::set<std::string, std::less<>>& visited)
{
    if (!node) return;
    const std::string name = node->getNamePath();
    if (!visited.insert(name).second) return;

    for (const MaterialX::InputPtr& input : node->getActiveInputs()) {
        AppendProgramNode(ConnectedNode(input), program, visited);
    }

    MaterialXProgramNode generated{
        .name = name,
        .category = node->getCategory(),
        .type = node->getType(),
    };
    if (const MaterialX::NodeDefPtr nodeDef = node->getNodeDef()) {
        generated.nodeDef = nodeDef->getName();
    }
    for (const MaterialX::InputPtr& input : node->getActiveInputs()) {
        std::string upstreamOutput;
        const MaterialX::NodePtr upstream = ConnectedNode(input, &upstreamOutput);
        generated.inputs.push_back({
            .name = input->getName(),
            .type = input->getType(),
            .value = upstream ? std::string() : input->getResolvedValueString(),
            .upstreamNode = upstream ? upstream->getNamePath() : std::string(),
            .upstreamOutput = std::move(upstreamOutput),
        });
    }
    program.nodes.push_back(std::move(generated));
}

MaterialXGeneratedProgram BuildGeneratedProgram(
    const MaterialX::DocumentPtr& source,
    const MaterialX::TypedElementPtr& renderable)
{
    MaterialXGeneratedProgram program;
    if (!source || !renderable) return program;

    const MaterialX::DocumentPtr document = source->copy();
    FlattenMaterialXSurfaceModels(document);

    const MaterialX::ElementPtr descendant = document->getDescendant(
        renderable->getNamePath());
    MaterialX::TypedElementPtr expandedRenderable = descendant
        ? descendant->asA<MaterialX::TypedElement>() : MaterialX::TypedElementPtr{};
    MaterialX::NodePtr outputNode = expandedRenderable
        ? expandedRenderable->asA<MaterialX::Node>() : MaterialX::NodePtr{};
    if (outputNode && outputNode->getType() == MaterialX::MATERIAL_TYPE_STRING) {
        for (const MaterialX::InputPtr& input : outputNode->getActiveInputs()) {
            const std::string& type = input->getType();
            if (type == MaterialX::SURFACE_SHADER_TYPE_STRING ||
                type == MaterialX::VOLUME_SHADER_TYPE_STRING) {
                outputNode = ConnectedNode(input);
                if (outputNode) break;
            }
        }
    }
    if (!outputNode) return program;

    program.outputNode = outputNode->getNamePath();
    std::set<std::string, std::less<>> visited;
    AppendProgramNode(outputNode, program, visited);
    return program;
}

void ReplaceAll(std::string& source, std::string_view needle, std::string_view replacement)
{
    if (needle.empty()) return;
    std::size_t position = 0;
    while ((position = source.find(needle, position)) != std::string::npos) {
        source.replace(position, needle.size(), replacement);
        position += replacement.size();
    }
}

void RenameInterfaceDeclaration(
    std::string& source,
    std::string_view qualifier,
    std::string_view oldName,
    std::string_view newName)
{
    const std::string qualifierMarker = " " + std::string(qualifier) + " ";
    const std::string declarationEnd = " " + std::string(oldName) + ";";
    std::size_t lineStart = 0;
    while (lineStart < source.size()) {
        const std::size_t lineEnd = source.find('\n', lineStart);
        const std::size_t length = (lineEnd == std::string::npos ? source.size() : lineEnd) -
            lineStart;
        const std::string_view line(source.data() + lineStart, length);
        if (line.find("layout") != std::string_view::npos &&
            line.find(qualifierMarker) != std::string_view::npos &&
            line.ends_with(declarationEnd)) {
            source.replace(lineStart + length - oldName.size() - 1,
                           oldName.size(), newName);
            lineStart += newName.size() - oldName.size();
        }
        if (lineEnd == std::string::npos) break;
        lineStart = source.find('\n', lineStart) + 1;
    }
}

void FlattenVulkanVertexData(MaterialX::Shader& shader, std::string& vertex, std::string& pixel)
{
    // MaterialX 1.39.3's Vk generator declares stage connectors as individual
    // location-qualified variables, but still emits the struct instance prefix
    // inherited from the desktop GLSL generator. Flatten the prefix while
    // retaining a distinct connector namespace: an output such as
    // i_geomprop_st otherwise collides with the vertex input of the same name.
    const auto& block = shader.getStage(MaterialX::Stage::VERTEX)
        .getOutputBlock(MaterialX::HW::VERTEX_DATA);
    if (block.empty()) return;
    for (const MaterialX::ShaderPort* port : block.getVariableOrder()) {
        const std::string& name = port->getVariable();
        const std::string flattenedName = "vd_" + name;
        const std::string qualifiedName =
            MaterialX::HW::VERTEX_DATA_INSTANCE + "." + name;
        RenameInterfaceDeclaration(vertex, "out", name, flattenedName);
        RenameInterfaceDeclaration(pixel, "in", name, flattenedName);
        ReplaceAll(vertex, qualifiedName, flattenedName);
        ReplaceAll(pixel, qualifiedName, flattenedName);
    }
}

std::vector<MaterialXShaderInput> ReflectPublicUniforms(
    const MaterialX::ShaderStage& stage)
{
    std::vector<MaterialXShaderInput> result;
    const auto& uniforms = stage.getUniformBlock(MaterialX::HW::PUBLIC_UNIFORMS);
    result.reserve(uniforms.size());
    for (const MaterialX::ShaderPort* port : uniforms.getVariableOrder()) {
        if (port->getType() == MaterialX::Type::FILENAME) continue;
        result.push_back({
            .name = port->getVariable(),
            .type = port->getType().getName(),
            .value = port->getValueString(),
            .colorSpace = port->getColorSpace(),
        });
    }
    return result;
}

std::vector<MaterialXShaderInput> ReflectTextures(
    const MaterialX::ShaderStage& stage)
{
    std::vector<MaterialXShaderInput> result;
    for (const auto& [blockName, block] : stage.getUniformBlocks()) {
        (void)blockName;
        for (const MaterialX::ShaderPort* port : block->getVariableOrder()) {
            if (port->getType() != MaterialX::Type::FILENAME) continue;
            result.push_back({
                .name = port->getVariable(),
                .type = port->getType().getName(),
                .value = port->getValueString(),
                .colorSpace = port->getColorSpace(),
            });
        }
    }
    return result;
}

} // namespace

MaterialXCompiler::MaterialXCompiler(ShaderCache& cache) noexcept : _glsl(cache) {}

std::string MaterialXCompiler::GeneratorVersion()
{
    return "MaterialX-" + MaterialX::getVersionString() + "-" +
        MaterialX::VkShaderGenerator::TARGET + "-" +
        MaterialX::VkShaderGenerator::VERSION;
}

MaterialXCompiledShader MaterialXCompiler::CompileXml(
    std::string_view xml,
    std::string_view shaderName,
    ShadingMode mode) const
{
    if (xml.empty()) throw std::invalid_argument("MaterialX XML must not be empty");
    auto document = MaterialX::createDocument();
    const std::string terminatedXml(xml);
    MaterialX::readFromXmlBuffer(
        document, terminatedXml.c_str(), MaterialXSearchPaths());
    document->setDataLibrary(pxr::HdMtlxStdLibraries());
    return CompileDocument(document, shaderName, mode);
}

MaterialXCompiledShader MaterialXCompiler::CompileDocument(
    const MaterialX::DocumentPtr& document,
    std::string_view shaderName,
    ShadingMode mode) const
{
    if (!document) throw std::invalid_argument("MaterialX document must not be null");

    const MaterialX::DocumentPtr generationDocument = document->copy();
    FlattenMaterialXUsdPrimvarReaders(generationDocument);

    const auto renderables = MaterialX::findRenderableElements(generationDocument);
    if (renderables.empty()) {
        throw std::runtime_error("MaterialX document has no renderable element");
    }

    const auto generator = MaterialX::VkShaderGenerator::create();
    MaterialX::GenContext context(generator);
    context.registerSourceCodeSearchPath(MaterialXSearchPaths());
    generator->registerTypeDefs(generationDocument);

    const std::string validName = MaterialX::createValidName(
        shaderName.empty() ? renderables.front()->getName() : std::string(shaderName));
    const auto shader = generator->generate(validName, renderables.front(), context);
    if (!shader) throw std::runtime_error("MaterialX Vulkan shader generation returned null");

    MaterialXCompiledShader result;
    result.mode = mode;
    result.name = validName;
    result.vertexSource = shader->getSourceCode(MaterialX::Stage::VERTEX);
    result.pixelSource = shader->getSourceCode(MaterialX::Stage::PIXEL);
    const auto& pixelStage = shader->getStage(MaterialX::Stage::PIXEL);
    result.publicUniforms = ReflectPublicUniforms(pixelStage);
    result.textures = ReflectTextures(pixelStage);
    if (mode != ShadingMode::RasterPreview) {
        result.program = BuildGeneratedProgram(
            generationDocument, renderables.front());
    }
    FlattenVulkanVertexData(*shader, result.vertexSource, result.pixelSource);
    if (result.vertexSource.empty() || result.pixelSource.empty()) {
        throw std::runtime_error("MaterialX generated an empty Vulkan shader stage");
    }

    GlslCompileOptions options;
    const std::string modeName(ShadingModeName(mode));
    options.generatorVersion = GeneratorVersion() + "-" + modeName;
    options.materialAbi = "hdcodex.materialx-raster.v1." + modeName;
    if (mode == ShadingMode::Modular) {
        options.generateDebugInfo = true;
        options.optimization = GlslCompileOptions::Optimization::None;
    }
    try {
        result.vertexSpirv = _glsl.Compile(
            result.vertexSource, GlslShaderStage::Vertex, validName + ".vert", options);
    } catch (const std::runtime_error& error) {
        throw std::runtime_error(std::string(error.what()) +
            "\nGenerated MaterialX vertex source:\n" + result.vertexSource);
    }
    try {
        result.pixelSpirv = _glsl.Compile(
            result.pixelSource, GlslShaderStage::Fragment, validName + ".frag", options);
    } catch (const std::runtime_error& error) {
        throw std::runtime_error(std::string(error.what()) +
            "\nGenerated MaterialX pixel source:\n" + result.pixelSource);
    }
    result.vertexDescriptors = ReflectSpirvDescriptors(result.vertexSpirv.words);
    result.pixelDescriptors = ReflectSpirvDescriptors(result.pixelSpirv.words);
    return result;
}

} // namespace hdcodex
